### PR TITLE
Resizable textareas

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by rmdmachado** [comment]
:+1:

**Comment by joaojusto** [comment]
This did not fix the issue, it was just an hack :stuck_out_tongue:

**Comment by naps62** [comment]
How so?

**Comment by joaojusto** [comment]
Because the text areas should not be resizable but instead occupy the whole screen (which is not happening right now).

**Comment by naps62** [comment]
This is a fix to not being able to have an expanded textarea, which was the problem reported by roberto
You might argue that it's not the solution that was though by the designer, but that doesn't make it a hack

Also, occupying the whole screen goes against the (also previously reported) issue that you should be able to see the discussion while you're commenting it. But that's a discussion for another time

**Pull request merged**
