### PR TITLE
Fixes cursor on menu icon

### LINKED ISSUE #131: Side menu icon cursor
When we hover on the menu icon the cursor should change to pointer

### PR DESCRIPTION
**Pull request by joaojusto**
Fixes #131

### CODE REVIEW

**Comment by gabrielpoca** [comment]
This [line](https://github.com/groupbuddies/council/blob/00bd62c961d5640afefff6f3f79f6e2b035cb557/app/assets/javascripts/app/discussions/index.html.slim#L6), why is this not an `a`?

**Comment by joaojusto** [comment]
No idea, but good point

**Comment by joaojusto** [comment]
If we switch to an a we have to add a rule 'color: $white' because we gave style to a's

**Comment by gabrielpoca** [comment]
It makes more sense that adding a `cursor: pointer`

**Comment by gabrielpoca** [comment]
:+1:

**Pull request merged**
