### PR TITLE
Can only submit new discussion once

### PR DESCRIPTION
**Pull request by joaojusto**
[Fix this bug](https://trello.com/c/Asl4O8lv/72-if-i-click-three-times-on-the-button-to-submit-a-new-discussion-it-creates-three-discussions)

### CODE REVIEW

**Comment by gabrielpoca** [comment]
Are you sure this fixes the issue? Because I believe the button can still be clicked multiple times.

**Comment by joaojusto** [comment]
Yes I'm sure, i tested it. This way it's not possible to click multiple times since the button will be disabled until the call to update/create completes successfully

**Comment by gabrielpoca** [comment]
But I don't understand this. Why are you making the form invalid?

**Comment by joaojusto** [comment]
Because when the form is invalid, the submit button is disabled and cannot be click

**Comment by gabrielpoca** [comment]
I don't think you're supposed to do that, are you? Besides, you can easily fix this in a way that's easier understand.

**Comment by joaojusto** [comment]
Ok I'll try to imrpove this

**Comment by joaojusto** [comment]
@gabrielpoca bump

**Comment by gabrielpoca** [comment]
:+1:

**Pull request merged**
