### PR TITLE
Sets up deploy to our own machine

### PR DESCRIPTION
**Pull request by naps62**
Already online at http://new.council.groupbuddies.com

This follows the standard process I've used for the blog and for our own 
website.

All 3 apps will now be served by the Obi Wan machine.

### CODE REVIEW

**Comment by gabrielpoca** [comment]
:+1: I trust you

**Comment by joaojusto** [comment]
@naps62 I think you can close this

**Comment by naps62** [comment]
@joaojusto No I can't. Need to take some time to set up a couple of things on the server before that. Hopefully I'll be able to do that this week

**Comment by joaojusto** [comment]
:tada:

**Pull request merged**
