### PR TITLE
Elastic text area in discussion form

### PR DESCRIPTION
**Pull request by bsonntag**
Adds Angular Elastic module to make textarea in new discussion form elastic.
Also adds page directive and fixes discussion views' layouts and style.

This fixes issue https://github.com/groupbuddies/council/issues/135.

### CODE REVIEW

**Comment by bsonntag** [comment]
@gabrielpoca Is this ok?

**Comment by gabrielpoca** [comment]
@bsonntag what about removing the `[layout=column]` in favor of a child of page, like `.Page-content` ?

**Comment by bsonntag** [comment]
@gabrielpoca Done. Should I also change discussion index and show to use page directive, or should I do that in another PR?

**Comment by gabrielpoca** [comment]
@bsonntag do it in this one.

**Comment by bsonntag** [comment]
@gabrielpoca Done.

**Comment by gabrielpoca** [comment]
:+1: nice work

**Pull request merged**
